package com.chloemlla.aura.data.repository

import android.content.Context
import androidx.room.Room
import com.chloemlla.aura.data.local.FreeVibeDatabase
import com.chloemlla.aura.data.model.WallpaperCollectionEntity
import com.chloemlla.aura.data.model.WallpaperCollectionItemEntity
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.test.runTest
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.RuntimeEnvironment
import org.robolectric.annotation.Config

/**
 * Deleting a whole collection was immediate and total even though removing a
 * single item already offered Undo. Deletion now hands back a snapshot that
 * restores the collection *and* its membership.
 */
@RunWith(RobolectricTestRunner::class)
@Config(sdk = [35])
class CollectionDeletionRestoreTest {

    private val context: Context get() = RuntimeEnvironment.getApplication()

    private lateinit var db: FreeVibeDatabase
    private lateinit var repository: CollectionRepository

    @Before
    fun setUp() {
        db = Room.inMemoryDatabaseBuilder(context, FreeVibeDatabase::class.java)
            .allowMainThreadQueries()
            .build()
        repository = CollectionRepository(db.collectionDao())
    }

    @After
    fun tearDown() = db.close()

    private suspend fun seedCollection(name: String, itemIds: List<String>): Long {
        val id = db.collectionDao().createCollection(WallpaperCollectionEntity(name = name))
        itemIds.forEach { wallpaperId ->
            db.collectionDao().addItem(
                WallpaperCollectionItemEntity(
                    collectionId = id,
                    wallpaperId = wallpaperId,
                    thumbnailUrl = "https://w.example/$wallpaperId-t.jpg",
                    fullUrl = "https://w.example/$wallpaperId.jpg",
                    source = "WALLHAVEN",
                ),
            )
        }
        return id
    }

    @Test
    fun `deleting returns a snapshot of the collection and its items`() = runTest {
        val id = seedCollection("Night", listOf("a", "b", "c"))

        val snapshot = repository.deleteWithSnapshot(id)

        assertEquals("Night", snapshot?.collection?.name)
        assertEquals(setOf("a", "b", "c"), snapshot?.items?.map { it.wallpaperId }?.toSet())
        assertTrue(repository.getAll().first().isEmpty())
    }

    @Test
    fun `restoring puts the collection and every membership row back`() = runTest {
        val id = seedCollection("Night", listOf("a", "b"))
        val snapshot = repository.deleteWithSnapshot(id)!!

        val restoredId = repository.restore(snapshot)

        val collections = repository.getAll().first()
        assertEquals(listOf("Night"), collections.map { it.name })
        assertEquals(
            setOf("a", "b"),
            repository.getItems(restoredId).first().map { it.wallpaperId }.toSet(),
        )
    }

    @Test
    fun `restored items point at the new collection id`() = runTest {
        val id = seedCollection("Night", listOf("a"))
        val snapshot = repository.deleteWithSnapshot(id)!!

        val restoredId = repository.restore(snapshot)

        // Room assigns a fresh autogenerated id; the items must follow it.
        assertNotEquals(0L, restoredId)
        val items = repository.getItems(restoredId).first()
        assertEquals(1, items.size)
        assertEquals(restoredId, items.single().collectionId)
    }

    @Test
    fun `deleting an unknown collection reports nothing to undo`() = runTest {
        assertNull(repository.deleteWithSnapshot(9_999L))
    }

    @Test
    fun `deleting one collection leaves the others intact`() = runTest {
        val night = seedCollection("Night", listOf("a"))
        seedCollection("Day", listOf("b"))

        repository.deleteWithSnapshot(night)

        assertEquals(listOf("Day"), repository.getAll().first().map { it.name })
    }

    @Test
    fun `an empty collection round-trips`() = runTest {
        val id = seedCollection("Empty", emptyList())
        val snapshot = repository.deleteWithSnapshot(id)!!

        val restoredId = repository.restore(snapshot)

        assertEquals("Empty", repository.getAll().first().single().name)
        assertTrue(repository.getItems(restoredId).first().isEmpty())
    }
}
