package com.chloemlla.aura.data.repository

import com.chloemlla.aura.data.local.CollectionDao
import com.chloemlla.aura.data.model.Wallpaper
import com.chloemlla.aura.data.model.WallpaperCollectionEntity
import com.chloemlla.aura.data.model.WallpaperCollectionItemEntity
import com.chloemlla.aura.service.DeletedCollectionSnapshot
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.first
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class CollectionRepository @Inject constructor(
    private val dao: CollectionDao,
) {
    fun getAll(): Flow<List<WallpaperCollectionEntity>> = dao.getAllCollections()

    fun getItems(collectionId: Long): Flow<List<WallpaperCollectionItemEntity>> =
        dao.getCollectionItems(collectionId)

    fun getItemCount(collectionId: Long): Flow<Int> = dao.getItemCount(collectionId)

    fun getCoverThumbnails(collectionId: Long): Flow<List<String>> =
        dao.getCoverThumbnails(collectionId)

    suspend fun create(name: String): Long =
        dao.createCollection(WallpaperCollectionEntity(name = name))

    suspend fun addWallpaper(collectionId: Long, wallpaper: Wallpaper) {
        dao.addItem(
            WallpaperCollectionItemEntity(
                collectionId = collectionId,
                wallpaperId = wallpaper.id,
                thumbnailUrl = wallpaper.thumbnailUrl,
                fullUrl = wallpaper.fullUrl,
                source = wallpaper.source.name,
                width = wallpaper.width,
                height = wallpaper.height,
            )
        )
    }

    suspend fun removeWallpaper(collectionId: Long, wallpaper: Wallpaper) =
        dao.removeItem(collectionId, wallpaper.id, wallpaper.source.name)

    /**
     * Deletes a collection and returns everything needed to put it back.
     *
     * Removing a single item already offered Undo while deleting the whole
     * collection was immediate and total, which is the wrong way round. The
     * snapshot is captured before the delete so the caller can restore the
     * collection and every membership row it contained.
     */
    suspend fun deleteWithSnapshot(collectionId: Long): DeletedCollectionSnapshot? {
        val collection = dao.getAllCollections().first()
            .firstOrNull { it.collectionId == collectionId }
            ?: return null
        val items = dao.getCollectionItems(collectionId).first()
        delete(collectionId)
        return DeletedCollectionSnapshot(
            collection = collection,
            items = items,
            deletedAtMs = System.currentTimeMillis(),
        )
    }

    /**
     * Recreates a deleted collection with its membership.
     *
     * Room assigns a new autogenerated collection id, and `importCollection`
     * re-points every item at it, so the restored rows do not carry the old id.
     */
    suspend fun restore(snapshot: DeletedCollectionSnapshot): Long =
        dao.importCollection(
            collection = snapshot.collection.copy(collectionId = 0),
            items = snapshot.items,
        )

    suspend fun delete(collectionId: Long) {
        dao.deleteCollectionItems(collectionId) // Explicit delete (PRAGMA foreign_keys is per-connection)
        dao.deleteCollection(collectionId)
    }

    suspend fun rename(collectionId: Long, name: String) =
        dao.renameCollection(collectionId, name)

    suspend fun isInCollection(collectionId: Long, wallpaper: Wallpaper): Boolean =
        dao.isInCollection(collectionId, wallpaper.id, wallpaper.source.name)
}
